export const actions = {
  post: {
    DATA_FETCHING: "POST_DATA_FETCHING",
    DATA_FETCHED: "POST_DATA_FETCHED",
    DATA_EDITED: "POST_DATA_EDITED",
    DATA_CREATED: "POST_DATA_CREATED",
    DATA_DELETED: "POST_DATA_DELETED",
    DATA_COMMENTED: "POST_DATA_COMMENTED",
    DATA_LIKED: "POST_DATA_LIKED",
    DATA_FETCH_ERROR: "POST_DATA_FETCH_ERROR",
  },
};
